apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: le-example-http
spec:
 acme:
   email: roelvanstapel@gmail.com
   server: https://acme-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     name: example-issuer-account-key
   solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token