apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 00-rbac.yml
- 01-traefik.yml
- caddyservice.yml
- certmanager.yml
- clusterrole.yml
- clusterrolebinding.yml
- jnlpservice.yml
- pv.yml
- pvc.yml
- secret.yml
- service.yml
- serviceaccount.yml
- traefikingress.yml
- whoami-service.yml
- whoami.yml
- 03-ingress.yml
- prodnamespace.yml