apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

resources:
- caddydeployment.yml
- deployment.yml
- accargocd.yml

namespace: acceptation

patches:
- target:
    kind: Ingress
    name: albingress
  path: ingress-patch.yml
- target:
    kind: Ingress
    name: albingress
  path: ingress-patch2.yml
- target:
    kind: Ingress
    name: traefikingress
  path: traefikingress-patch.yml

configMapGenerator:
- name: caddy-config
  files:
  - Caddyfile