apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

resources:
- caddydeployment.yml
- deployment.yml
- prodargocd.yml

namespace: production

configMapGenerator:
- name: caddy-config
  files:
  - Caddyfile