apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prodargocd
spec:
  project: default
  source:
    repoURL: https://github.com/RoelVanstapelPXL/stageroel.git
    targetRevision: HEAD
    path: stagekubernetes/prod
  destination:
    name: in-cluster
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true